#!/usr/bin/env bash
# ==============================================================================
# Bybit Multi-Pair Bot - Automated Debian/Ubuntu Production VPS Deploy Script
# ==============================================================================
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

# Debian / Ubuntu compatibility: use sudo only if not already running as root
if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
else
  if command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
  else
    echo "ERROR: Running as non-root user and 'sudo' is not installed."
    exit 1
  fi
fi

echo "=== [1/6] Preparing Debian 13 / Ubuntu VPS Environment ==="
$SUDO apt-get update -qq
$SUDO apt-get install -y -qq \
  python3 python3-venv python3-pip git chrony curl ca-certificates

# Ensure clock synchronization is active (prevents Bybit Error 10002)
$SUDO systemctl enable --now chrony || $SUDO systemctl enable --now systemd-timesyncd || true

CURRENT_USER=$(whoami)
CURRENT_GROUP=$(id -gn)
APP_DIR="$HOME/hyper_hedge_research"

echo "Target Directory: $APP_DIR (User: $CURRENT_USER:$CURRENT_GROUP)"

echo "=== [2/6] Syncing Code Repository ==="
if [ ! -d "$APP_DIR/.git" ]; then
  echo "Cloning repository from GitHub..."
  rm -rf "$APP_DIR"
  git clone https://github.com/0x7sec/hyper-hedge.git "$APP_DIR"
  cd "$APP_DIR"
else
  cd "$APP_DIR"
  echo "Fetching latest changes..."
  git fetch origin main
  git reset --hard origin/main
fi

cd "$APP_DIR"
# Keep existing trade records ledger intact across updates
echo "Preserving trade history ledger..."
echo "=== [3/6] Setting Up Python Virtual Environment ==="
if [ ! -d "venv" ]; then
  python3 -m venv venv
fi
./venv/bin/pip install --upgrade pip -q
./venv/bin/pip install -r requirements.txt -q

echo "=== [4/6] Injecting Active Configuration & Credentials (.env) ==="
EXISTING_TPASS=""
if [ -f .env ]; then
  EXISTING_TPASS=$(grep "^TELEMETRY_PASSWORD=" .env 2>/dev/null | cut -d'=' -f2- || true)
fi

if [ -n "${TELEMETRY_PASS:-}" ]; then
  FINAL_TPASS="${TELEMETRY_PASS}"
elif [ -n "$EXISTING_TPASS" ]; then
  FINAL_TPASS="$EXISTING_TPASS"
else
  FINAL_TPASS=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | tr -dc A-Za-z0-9 | head -c 24 || echo "sec_hedge_$(date +%s)")
fi

cat << 'ENVCONF' > .env
# ==============================================================================
# BYBIT V5 SINGLE-LEG TREND RUNNER & CONCURRENCY ENGINE (8 CHAMPION PAIRS)
# Auto-generated by Deployment Workflow (Debian 13)
# ==============================================================================
BYBIT_API_KEY=zu7QF2MXivrNUpxe2y
BYBIT_API_SECRET=mzYaF9c7tFLrLThjKsFLueoFeFyFs5c8RcYo
SYMBOLS=AVAXUSDT,LINKUSDT,HYPEUSDT,XMRUSDT,DOGEUSDT,BTCUSDT,ETHUSDT,SOLUSDT
LEVERAGE=4
MAX_CONCURRENT_PAIRS=4
TESTNET=true
POLL_INTERVAL=5
COOLDOWN_SECS=0
MAX_CYCLES=0
DRY_RUN=false
LOG_CSV=bybit_trades.csv
TELEMETRY_PORT=8080
ENVCONF

echo "TELEMETRY_PASSWORD=${FINAL_TPASS}" >> .env

# If custom BYBIT_KEY and BYBIT_SECRET are passed as environment variables, override them
if [ -n "${BYBIT_KEY:-}" ]; then
  sed -i "s/^BYBIT_API_KEY=.*/BYBIT_API_KEY=${BYBIT_KEY}/" .env
fi
if [ -n "${BYBIT_SECRET:-}" ]; then
  sed -i "s/^BYBIT_API_SECRET=.*/BYBIT_API_SECRET=${BYBIT_SECRET}/" .env
fi
chmod 600 .env

echo "=== [5/6] Configuring & Starting systemd Daemons ==="
# 1. Trading Bot Engine Service
$SUDO tee /etc/systemd/system/bybit-bot.service > /dev/null << SERVICE
[Unit]
Description=Bybit Multi-Pair Concurrent Dual-Leg Hedge Bot
After=network.target network-online.target time-sync.target
Wants=network-online.target time-sync.target

[Service]
Type=simple
User=$CURRENT_USER
Group=$CURRENT_GROUP
WorkingDirectory=$APP_DIR
EnvironmentFile=$APP_DIR/.env
ExecStart=$APP_DIR/venv/bin/python run_bybit_bot.py
Restart=always
RestartSec=10

# Resource governance & crash resilience
LimitNOFILE=65535
TimeoutStopSec=30
KillMode=process

# Logging: routed to systemd journal
StandardOutput=journal
StandardError=journal
SyslogIdentifier=bybit-bot

[Install]
WantedBy=multi-user.target
SERVICE

# 2. Telemetry & AI Monitoring Server Service
$SUDO tee /etc/systemd/system/bybit-telemetry.service > /dev/null << TELEMSERVICE
[Unit]
Description=Bybit Multi-Pair Bot HTTP Telemetry & AI Monitoring Server
After=network.target network-online.target time-sync.target
Wants=network-online.target time-sync.target

[Service]
Type=simple
User=$CURRENT_USER
Group=$CURRENT_GROUP
WorkingDirectory=$APP_DIR
EnvironmentFile=$APP_DIR/.env
ExecStart=$APP_DIR/venv/bin/python telemetry_server.py
Restart=always
RestartSec=5

# Resource governance & crash resilience
LimitNOFILE=65535
TimeoutStopSec=15
KillMode=process

# Logging: routed to systemd journal
StandardOutput=journal
StandardError=journal
SyslogIdentifier=bybit-telemetry

[Install]
WantedBy=multi-user.target
TELEMSERVICE

# Configure Logrotate for trade audit CSV
$SUDO tee /etc/logrotate.d/bybit-bot > /dev/null << LOGROT
$APP_DIR/bybit_trades.csv {
    weekly
    missingok
    rotate 12
    compress
    delaycompress
    notifempty
    copytruncate
}
LOGROT
$SUDO chmod 644 /etc/logrotate.d/bybit-bot

# Open firewall port 8080 if UFW is active
if command -v ufw >/dev/null 2>&1; then
  if $SUDO ufw status | grep -q "Status: active"; then
    echo "Opening port 8080 in UFW firewall..."
    $SUDO ufw allow 8080/tcp comment 'Bybit Telemetry API' || true
  fi
fi

# Pre-cache continuous historical Kline data for Research Suite
echo "=== Pre-caching Historical Kline Data for Research Suite ==="
./venv/bin/python scripts/download_latest_candles.py --symbols BTCUSDT,ETHUSDT,SOLUSDT,PAXGUSDT --bars 8000 || echo "Kline pre-caching completed or will fetch on demand."

# Reload and restart daemons
$SUDO systemctl daemon-reload
$SUDO systemctl enable bybit-bot bybit-telemetry
$SUDO systemctl restart bybit-bot bybit-telemetry

echo "=== [6/6] Verifying Daemon Status ==="
sleep 3
BOT_ACTIVE=false
TELEM_ACTIVE=false

if $SUDO systemctl is-active --quiet bybit-bot; then
  BOT_ACTIVE=true
fi
if $SUDO systemctl is-active --quiet bybit-telemetry; then
  TELEM_ACTIVE=true
fi

VPS_IP=$(curl -s -4 ifconfig.me 2>/dev/null || curl -s -4 icanhazip.com 2>/dev/null || echo "<vps-ip>")

if [ "$BOT_ACTIVE" = true ] && [ "$TELEM_ACTIVE" = true ]; then
  echo "=============================================================================="
  echo ">>> SUCCESS: All services ACTIVE and running on VPS! <<<"
  echo "=============================================================================="
  echo "  • bybit-bot.service      : ACTIVE (Trading Engine)"
  echo "  • bybit-telemetry.service: ACTIVE (HTTP Telemetry & AI API)"
  echo "------------------------------------------------------------------------------"
  echo "📊 Web Dashboard URL     : http://${VPS_IP}:8080/dashboard?password=${FINAL_TPASS}"
  echo "🤖 AI Monitoring Endpoint: http://${VPS_IP}:8080/api/ai-summary?password=${FINAL_TPASS}"
  echo "🔑 Telemetry Password    : ${FINAL_TPASS}"
  echo "=============================================================================="
  $SUDO systemctl status bybit-bot bybit-telemetry --no-pager
else
  echo "ERROR: One or more services failed to start."
  $SUDO systemctl status bybit-bot bybit-telemetry --no-pager
  exit 1
fi
