#!/usr/bin/env bash
# ==============================================================================
# Bybit Multi-Pair Bot - Automated Debian/Ubuntu Production VPS Deploy Script
# ==============================================================================
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

# Debian / Ubuntu compatibility: use sudo only if not already running as root
if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
else
  if command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
  else
    echo "ERROR: Running as non-root user and 'sudo' is not installed."
    exit 1
  fi
fi

echo "=== [1/6] Preparing Debian 13 / Ubuntu VPS Environment ==="
$SUDO apt-get update -qq
$SUDO apt-get install -y -qq \
  python3 python3-venv python3-pip git chrony curl ca-certificates

# Ensure clock synchronization is active (prevents Bybit Error 10002)
$SUDO systemctl enable --now chrony || $SUDO systemctl enable --now systemd-timesyncd || true

CURRENT_USER=$(whoami)
CURRENT_GROUP=$(id -gn)
APP_DIR="$HOME/hyper_hedge_research"

echo "Target Directory: $APP_DIR (User: $CURRENT_USER:$CURRENT_GROUP)"

echo "=== [2/6] Syncing Code Repository ==="
if [ ! -d "$APP_DIR/.git" ]; then
  echo "Cloning repository from GitHub..."
  rm -rf "$APP_DIR"
  git clone https://github.com/0x7sec/hyper-hedge.git "$APP_DIR"
  cd "$APP_DIR"
else
  cd "$APP_DIR"
  echo "Fetching latest changes..."
  git fetch origin main
  git reset --hard origin/main
fi

cd "$APP_DIR"
echo "=== [3/6] Setting Up Python Virtual Environment ==="
if [ ! -d "venv" ]; then
  python3 -m venv venv
fi
./venv/bin/pip install --upgrade pip -q
./venv/bin/pip install -r requirements.txt -q

echo "=== [4/6] Injecting Active Configuration & Credentials (.env) ==="
cat << 'ENVCONF' > .env
# ==============================================================================
# BYBIT V5 MULTI-PAIR HEDGE BOT CONFIGURATION (BTC, ETH, SOL)
# Auto-generated by Deployment Workflow (Debian 13)
# ==============================================================================
BYBIT_API_KEY=zu7QF2MXivrNUpxe2y
BYBIT_API_SECRET=mzYaF9c7tFLrLThjKsFLueoFeFyFs5c8RcYo
SYMBOLS=BTCUSDT,ETHUSDT,SOLUSDT
LEVERAGE=4
MAX_CONCURRENT_PAIRS=3
TESTNET=true
POLL_INTERVAL=5
COOLDOWN_SECS=0
MAX_CYCLES=0
DRY_RUN=false
LOG_CSV=bybit_trades.csv
ENVCONF

# If custom BYBIT_KEY and BYBIT_SECRET are passed as environment variables, override them
if [ -n "${BYBIT_KEY:-}" ]; then
  sed -i "s/^BYBIT_API_KEY=.*/BYBIT_API_KEY=${BYBIT_KEY}/" .env
fi
if [ -n "${BYBIT_SECRET:-}" ]; then
  sed -i "s/^BYBIT_API_SECRET=.*/BYBIT_API_SECRET=${BYBIT_SECRET}/" .env
fi
chmod 600 .env

echo "=== [5/6] Configuring & Starting systemd Daemon ==="
$SUDO tee /etc/systemd/system/bybit-bot.service > /dev/null << SERVICE
[Unit]
Description=Bybit Multi-Pair Concurrent Dual-Leg Hedge Bot
After=network.target network-online.target time-sync.target
Wants=network-online.target time-sync.target

[Service]
Type=simple
User=$CURRENT_USER
Group=$CURRENT_GROUP
WorkingDirectory=$APP_DIR
EnvironmentFile=$APP_DIR/.env
ExecStart=$APP_DIR/venv/bin/python run_bybit_bot.py
Restart=always
RestartSec=10

# Resource governance & crash resilience
LimitNOFILE=65535
TimeoutStopSec=30
KillMode=process

# Logging: routed to systemd journal
StandardOutput=journal
StandardError=journal
SyslogIdentifier=bybit-bot

[Install]
WantedBy=multi-user.target
SERVICE

# Configure Logrotate for trade audit CSV
$SUDO tee /etc/logrotate.d/bybit-bot > /dev/null << LOGROT
$APP_DIR/bybit_trades.csv {
    weekly
    missingok
    rotate 12
    compress
    delaycompress
    notifempty
    copytruncate
}
LOGROT
$SUDO chmod 644 /etc/logrotate.d/bybit-bot

# Reload and restart daemon
$SUDO systemctl daemon-reload
$SUDO systemctl enable bybit-bot
$SUDO systemctl restart bybit-bot

echo "=== [6/6] Verifying Daemon Status ==="
sleep 3
if $SUDO systemctl is-active --quiet bybit-bot; then
  echo ">>> SUCCESS: bybit-bot is ACTIVE and running on VPS! <<<"
  $SUDO systemctl status bybit-bot --no-pager
else
  echo "ERROR: bybit-bot failed to start. Recent journal logs:"
  $SUDO journalctl -u bybit-bot -n 50 --no-pager
  exit 1
fi
